"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from decouple import AutoConfig


# Build paths inside the project like this: BASE_DIR / 'subdir'.
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
# Use AutoConfig so missing .env files don't crash in production
# AutoConfig reads OS environment first, then optional .env in search_path
config = AutoConfig(search_path=str(BASE_DIR))


from dotenv import load_dotenv

load_dotenv()

# SECURITY WARNING: keep the secret key secret, and never commit a default.
# This no longer signs API credentials — WorkOS does that — but Django still
# uses it for sessions, the admin, CSRF and password-reset tokens.
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# Comma-separated list, e.g. "usebyro.com,www.usebyro.com,byro.onrender.com".
# Falls back to localhost only when DEBUG is on, so a misconfigured production
# deploy fails loudly instead of silently accepting any Host header.
ALLOWED_HOSTS = [
    h.strip() for h in config(
        'ALLOWED_HOSTS',
        default='localhost,127.0.0.1' if DEBUG else '',
    ).split(',') if h.strip()
]

BLOCKRADAR_API_KEY = os.environ.get('BLOCKRADAR_API_KEY')
FRONTEND_URL = os.environ.get('FRONTEND_URL')
# Canonical public site URL used in outbound emails (ticket links, etc.).
# Defaults to the production custom domain so confirmation emails never point
# at an internal/preview host even if FRONTEND_URL is set elsewhere.
SITE_URL = os.environ.get('SITE_URL', 'https://usebyro.com')
PAYSTACK_SECRET_KEY = config('PAYSTACK_SECRET_KEY', default='')
PAYSTACK_PUBLIC_KEY = config('PAYSTACK_PUBLIC_KEY', default='')
PAYSTACK_CALLBACK_URL = config('PAYSTACK_CALLBACK_URL', default='http://localhost:3000/payment/callback')
PAYSTACK_CALLBACK_URL = config('PAYSTACK_CALLBACK_URL', default='https://usebyro.com/payment/callback')

# Email
RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '')
BREVO_SMTP_KEY = os.environ.get('BREVO_SMTP_KEY', '')


# WorkOS AuthKit — the sole identity provider.
#   WORKOS_CLIENT_ID: the client ID from the WorkOS dashboard. Public; it also
#     determines the JWKS and issuer URLs used to verify access tokens.
#   WORKOS_API_KEY: server-side secret, used only for Management API calls
#     (fetching a user's email at sign-in, sending co-host invitations).
#   WORKOS_ISSUER: optional. Pins the `iss` claim access tokens must carry —
#     your hosted AuthKit domain, which is auto-generated and differs per
#     environment. `manage.py check_workos` discovers it and flags a mismatch.
#     Unset is still safe: WorkOS publishes JWKS per client, so a valid
#     signature already proves the token was issued for this client.
WORKOS_CLIENT_ID = config('WORKOS_CLIENT_ID', default='')
WORKOS_API_KEY = config('WORKOS_API_KEY', default='')
WORKOS_ISSUER = config('WORKOS_ISSUER', default='')
WORKOS_API_BASE_URL = config('WORKOS_API_BASE_URL', default='https://api.workos.com')
# Where WorkOS sends the browser back after a Google/Apple sign-in. Must match a
# Redirect URI registered in the WorkOS dashboard. Read from settings and never
# from the request — a client-supplied redirect would be an open redirect and
# would let an attacker harvest authorization codes.
WORKOS_OAUTH_REDIRECT_URI = config(
    'WORKOS_OAUTH_REDIRECT_URI',
    default=(os.environ.get('FRONTEND_URL', 'http://localhost:3000').rstrip('/') + '/auth/callback'),
)

POSTHOG_PROJECT_TOKEN = config('POSTHOG_PROJECT_TOKEN', default='')
POSTHOG_HOST = config('POSTHOG_HOST', default='')


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'drf_yasg',
    'cloudinary',
    'cloudinary_storage',
    'bryo.apps.BryoConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'posthog.integrations.django.PosthogContextMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]



ROOT_URLCONF = 'api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'api.wsgi.application'




# Static files configuration
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
] if os.path.exists(os.path.join(BASE_DIR, 'static')) else []


_db_engine = os.getenv('DB_ENGINE', 'django.db.backends.postgresql')
_is_sqlite = _db_engine == 'django.db.backends.sqlite3'

DATABASES = {
    'default': {
        'ENGINE': _db_engine,
        'NAME': BASE_DIR / 'db.sqlite3' if _is_sqlite else os.getenv('DB_NAME'),
        'USER': '' if _is_sqlite else os.getenv('DB_USER'),
        'PASSWORD': '' if _is_sqlite else os.getenv('DB_PASSWORD'),
        'HOST': '' if _is_sqlite else os.getenv('DB_HOST'),
        'PORT': '' if _is_sqlite else os.getenv('DB_PORT'),
        **({} if _is_sqlite else {'OPTIONS': {'sslmode': 'require'}}),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
REST_FRAMEWORK = {
    # WorkOS access tokens are the only API credential. Django mints nothing.
    # Session/Basic auth are deliberately absent: the API is cross-origin and
    # token-only, and leaving SessionAuthentication on would expose every
    # endpoint to CSRF via the admin cookie.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'bryo.authentication.WorkOSAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    # Only scoped endpoints are throttled. The auth routes are unauthenticated
    # and each makes an outbound WorkOS call, so they are what need a ceiling.
    'DEFAULT_THROTTLE_RATES': {
        # Sending a code emails a third party and costs a WorkOS call, so this
        # is the one worth keeping tight.
        'auth_send': '15/hour',
        # Verification is guessing a code; WorkOS caps attempts too, this is
        # belt and braces.
        'auth_verify': '30/hour',
        'auth_refresh': '120/hour',
        'cohost_invite': '60/hour',
    },
}

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/



STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Moved into STORAGES below alongside the media backend.

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = os.getenv('ENVIRONMENT') == 'production'




CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    'https://www.byro.africa',
    'https://byro-two.vercel.app',
    'https://usebyro.com',
    'https://www.usebyro.com',
]


CORS_ALLOW_CREDENTIALS = True


CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]


AUTH_USER_MODEL = 'bryo.CustomUser'
 
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Supabase Storage — persists uploaded files across Render deploys/restarts.
SUPABASE_URL = os.getenv('SUPABASE_URL', '')
SUPABASE_KEY = os.getenv('SUPABASE_KEY', '')
SUPABASE_STORAGE_BUCKET = os.getenv('SUPABASE_STORAGE_BUCKET', 'event-images')

ADMIN_SECRET = os.getenv('ADMIN_SECRET', '')

# Cloudinary — primary media backend. django-cloudinary-storage reads these.
CLOUDINARY_CLOUD_NAME = os.getenv('CLOUDINARY_CLOUD_NAME', '')
CLOUDINARY_API_KEY = os.getenv('CLOUDINARY_API_KEY', '')
CLOUDINARY_API_SECRET = os.getenv('CLOUDINARY_API_SECRET', '')

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': CLOUDINARY_CLOUD_NAME,
    'API_KEY': CLOUDINARY_API_KEY,
    'API_SECRET': CLOUDINARY_API_SECRET,
}

_cloudinary_configured = bool(
    CLOUDINARY_CLOUD_NAME and CLOUDINARY_API_KEY and CLOUDINARY_API_SECRET
)

# Media backend priority: Cloudinary → Supabase → local filesystem.
if _cloudinary_configured:
    _default_storage_backend = 'cloudinary_storage.storage.MediaCloudinaryStorage'
elif SUPABASE_URL and SUPABASE_KEY:
    _default_storage_backend = 'bryo.storage.SupabaseMediaStorage'
else:
    _default_storage_backend = 'django.core.files.storage.FileSystemStorage'

STORAGES = {
    "default": {
        "BACKEND": _default_storage_backend,
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}



