services:
  - type: web
    name: byro
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input
    preDeployCommand: python manage.py migrate
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
