# Generated by Django 5.2 on 2026-06-22 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bryo', '0010_profile_formquestion_ticket_user_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_remaining_count',
            field=models.BooleanField(default=False, help_text='If enabled, expose remaining ticket counts to attendees'),
        ),
        migrations.CreateModel(
            name='TicketTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='bryo.event')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='bryo.tickettier'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tier',
            field=models.ForeignKey(blank=True, help_text='Null = event has no tiers (legacy flat pricing)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='bryo.tickettier'),
        ),
    ]
