# Generated by Django 5.2 on 2026-06-23 07:44

import django.db.models.deletion
from django.db import migrations, models


def backfill_ticket_payment(apps, schema_editor):
    """
    Copy the old Payment.ticket (1-to-1) link onto the new Ticket.payment
    FK before the old column is dropped, so existing data isn't lost.
    """
    Payment = apps.get_model('bryo', 'Payment')
    for payment in Payment.objects.exclude(ticket__isnull=True):
        ticket = payment.ticket
        ticket.payment_id = payment.pk
        ticket.save(update_fields=['payment'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bryo', '0011_event_show_remaining_count_tickettier_payment_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_purchased', to='bryo.payment'),
        ),
        migrations.RunPython(backfill_ticket_payment, noop_reverse),
        migrations.RemoveField(
            model_name='payment',
            name='ticket',
        ),
    ]
