# Generated by Django 5.2 on 2026-06-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bryo', '0012_remove_payment_ticket_ticket_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('web3_crypto', 'Web3 & Crypto'), ('entertainment', 'Entertainment'), ('art_culture', 'Art & Culture'), ('fitness', 'Fitness'), ('conference', 'Conference'), ('technology', 'Technology'), ('other', 'Other'), ('concerts', 'Concerts'), ('sports', 'Sports'), ('nightlife', 'Nightlife'), ('conferences', 'Conferences')], db_index=True, default='other', help_text='Event category for filtering', max_length=20),
        ),
    ]
