# Generated by Django 5.2 on 2026-08-13 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bryo', '0015_alter_userprofile_account_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventcohost',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='workos_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='eventcohost',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcohost',
            name='invited_email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='eventcohost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], db_index=True, default='accepted', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='auth_provider',
            field=models.CharField(blank=True, choices=[('workos', 'WorkOS'), ('privy', 'Privy'), ('web3auth', 'Web3Auth')], default='workos', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventcohost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cohosted_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='eventcohost',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('event', 'user'), name='unique_cohost_per_event'),
        ),
        migrations.AddConstraint(
            model_name='eventcohost',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('event', 'invited_email'), name='unique_pending_cohost_invite_per_event'),
        ),
    ]
