# Generated by Django 5.2 on 2026-07-14 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bryo', '0016_event_max_tickets_per_email_tickettier_admits_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='max_tickets_per_email',
        ),
    ]
