# Generated by Django 5.2 on 2026-08-14 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bryo', '0016_alter_eventcohost_unique_together_and_more'),
        ('bryo', '0017_remove_event_max_tickets_per_email'),
    ]

    operations = [
    ]
