# Generated by Django 5.2 on 2026-08-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bryo', '0018_merge_20260814_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('attendee', 'Attendee'), ('organizer', 'Organizer')], db_index=True, max_length=20),
        ),
    ]
