# Generated by Django 5.2 on 2026-08-27 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bryo', '0019_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed amount (NGN)'), ('percentage', 'Percentage')], default='fixed', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_redemptions', models.PositiveIntegerField(blank=True, help_text='Blank = unlimited', null=True)),
                ('redeemed_count', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='bryo.event')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('event', 'code')},
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='bryo.promocode'),
        ),
    ]
