# Generated by Django 5.2 on 2026-09-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bryo', '0020_promocode_payment_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='milestones_notified',
            field=models.JSONField(blank=True, default=list, help_text='Ticket-sold milestone thresholds already emailed to the organizer'),
        ),
        migrations.AddField(
            model_name='event',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the 24h-before attendee/organizer reminder was sent', null=True),
        ),
    ]
