# Generated by Django 5.2 on 2026-09-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bryo', '0021_event_milestones_notified_event_reminder_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('entertainment', 'Entertainment'), ('fitness', 'Fitness'), ('art_culture', 'Art & Culture'), ('conference', 'Conference'), ('web3_crypto', 'Web3 & Crypto'), ('technology', 'Technology'), ('other', 'Other')], db_index=True, default='other', help_text='Event category for filtering', max_length=20),
        ),
    ]
