# Generated by Django 5.2 on 2026-09-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bryo', '0022_simplify_event_category_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pass_fee_to_attendee',
            field=models.BooleanField(default=True, help_text="If enabled, Byro's service fee is added to the attendee's ticket price. If disabled, the fee is deducted from the organizer's payout instead."),
        ),
    ]
