# Generated by Django 5.2 on 2026-09-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bryo', '0025_userprofile_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='auth_provider',
            field=models.CharField(blank=True, choices=[('workos', 'WorkOS'), ('privy', 'Privy'), ('web3auth', 'Web3Auth'), ('guest', 'Guest (ticket checkout, no login)')], default='workos', max_length=50),
        ),
    ]
