# Generated by Django 5.2 on 2026-09-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bryo', '0026_alter_customuser_auth_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
