# Generated by Django 5.2 on 2026-09-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bryo', '0027_event_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcohost',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('checkin', 'Check-in only')], default='manager', max_length=20),
        ),
    ]
