# Generated by Django 5.2 on 2026-09-20 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bryo', '0028_cohost_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_tickets_per_person',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='tickettier',
            name='max_tickets_per_person',
            field=models.PositiveSmallIntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
