# Generated by Django 5.2 on 2026-09-20 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bryo', '0029_ticket_limits_per_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettier',
            name='min_tickets_per_person',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
