# Generated by Django 5.2 on 2026-09-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bryo', '0030_tier_min_tickets_per_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettier',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
