# Generated by Django 5.2 on 2026-09-23 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bryo', '0031_tier_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='merch/')),
                ('purchase_link', models.URLField(blank=True, help_text='Where buyers go to purchase this item')),
                ('stock', models.PositiveIntegerField(blank=True, help_text='Blank = unlimited', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Shown on the public profile when on')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merch_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
