# Generated by Django 5.2 on 2026-10-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bryo', '0034_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('event.suspended', 'Event suspended'), ('event.reactivated', 'Event reactivated'), ('event.deleted', 'Event deleted'), ('user.suspended', 'User suspended'), ('user.reactivated', 'User reactivated'), ('user.role_changed', 'User role changed'), ('payout.processed', 'Payout processed'), ('payout.rejected', 'Payout rejected'), ('payout.deleted', 'Payout deleted')], db_index=True, max_length=32)),
                ('target_type', models.CharField(max_length=16)),
                ('target_id', models.CharField(max_length=64)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id', '-created_at'], name='bryo_admina_target__309c0c_idx')],
            },
        ),
    ]
