# Generated by Django 5.2 on 2026-10-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bryo', '0035_admin_action_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('viewer', 'Viewer — read only'), ('admin', 'Admin — moderate events and users, process payouts'), ('owner', 'Owner — everything, incl. deletes, roles and team')], default='viewer', max_length=10)),
                ('added_by_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='adminaction',
            name='actor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='adminaction',
            name='action',
            field=models.CharField(choices=[('event.suspended', 'Event suspended'), ('event.reactivated', 'Event reactivated'), ('event.deleted', 'Event deleted'), ('user.suspended', 'User suspended'), ('user.reactivated', 'User reactivated'), ('user.role_changed', 'User role changed'), ('payout.processed', 'Payout processed'), ('payout.rejected', 'Payout rejected'), ('payout.deleted', 'Payout deleted'), ('team.added', 'Team member added'), ('team.role_changed', 'Team role changed'), ('team.removed', 'Team member removed')], db_index=True, max_length=32),
        ),
    ]
