# Generated by Django 5.2 on 2026-10-04 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bryo', '0036_admin_members_and_actor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('action', models.CharField(choices=[('auth.sign_in', 'Signed in'), ('event.created', 'Event created'), ('event.updated', 'Event edited'), ('event.deleted', 'Event deleted'), ('ticket.purchased', 'Tickets purchased'), ('ticket.claimed', 'Free tickets claimed'), ('ticket.transfer_started', 'Ticket transfer started'), ('ticket.transfer_completed', 'Ticket transfer accepted'), ('ticket.checked_in', 'Attendee checked in'), ('payout.requested', 'Payout requested')], db_index=True, max_length=32)),
                ('target_type', models.CharField(blank=True, max_length=16)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id', '-created_at'], name='bryo_activi_target__aef721_idx')],
            },
        ),
    ]
