# Generated by Django 5.2 on 2026-10-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bryo', '0037_activity_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventformquestion',
            name='question_type',
            field=models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('select', 'Dropdown'), ('checkbox', 'Checkbox (multiple)'), ('radio', 'Radio (single)'), ('yesno', 'Yes or no')], default='text', max_length=20),
        ),
    ]
