# Generated by Django 5.2 on 2026-10-07 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bryo', '0038_yesno_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancel_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cancellation_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment_status',
            field=models.CharField(choices=[('free', 'Free'), ('pending', 'Payment Pending'), ('paid', 'Paid'), ('failed', 'Payment Failed'), ('refunded', 'Refunded (event cancelled)'), ('cancelled', 'Cancelled (event cancelled)')], default='free', max_length=20),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitting', 'Submitting'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('needs_attention', 'Needs attention')], default='pending', max_length=20)),
                ('paystack_refund_id', models.CharField(blank=True, default='', max_length=64)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=500)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='bryo.event')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='bryo.payment')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['event', 'status'], name='bryo_refund_event_i_f4766a_idx')],
            },
        ),
    ]
