# Generated by Django 5.2 on 2026-10-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bryo', '0039_event_cancellation_and_refunds'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='arranged_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminaction',
            name='action',
            field=models.CharField(choices=[('event.suspended', 'Event suspended'), ('event.reactivated', 'Event reactivated'), ('event.deleted', 'Event deleted'), ('user.suspended', 'User suspended'), ('user.reactivated', 'User reactivated'), ('user.role_changed', 'User role changed'), ('payout.processed', 'Payout processed'), ('payout.rejected', 'Payout rejected'), ('payout.deleted', 'Payout deleted'), ('refunds.sent', 'Refunds sent'), ('refunds.retried', 'Refunds retried'), ('team.added', 'Team member added'), ('team.role_changed', 'Team role changed'), ('team.removed', 'Team member removed')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('awaiting', 'Awaiting approval'), ('pending', 'Pending'), ('submitting', 'Submitting'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('needs_attention', 'Needs attention')], default='awaiting', max_length=20),
        ),
    ]
